load("@bootlin_bazel//toolchains:toolchains.bzl", "bootlin_all_toolchain_defs")

filegroup(name = "empty")

filegroup(
    name = "wrappers",
    srcs = glob(["tool_wrappers/**"]),
)

bootlin_all_toolchain_defs()
